name: Test App

on:
  pull_request:

env:
  PYTHON_VERSION: 3.x

# Check out the code
# Install python
# Install dependencies
# Run app
jobs:
  job1:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run app
      run: | 
        python main.py

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Do nothing testing
      run: echo "This job does nothing"

  job3:
    needs: job2
    uses: ./.github/workflows/reusable-test.yml
    with:
      node: 14.x
    secrets: inherit

  
  


    

